In [1]:
import os
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error
import math


In [5]:
os.chdir(r'C:\Users\jaij2\OneDrive\바탕 화면\논문\야구데이터\전처리')
Saber = pd.read_csv('2019_타자_팀별_Saber.csv', encoding = 'cp949')
Saber.index = Saber['Unnamed: 0']
#Saber = Saber[Saber['PA'] >= math.trunc(144 * 3.1)]
#Saber = Saber[Saber['PA'] >= 144]
#Saber = Saber.replace(np.NaN, 0)
HIT3 = Saber['H3']
SB = Saber['SB']
rec = Saber[['RBI', 'RUN', 'HIT']]
Saber = Saber.iloc[:, -14:]
#Saber = Saber.drop(columns = ['Money_20'])
#Saber = Saber.drop('김태근') ## 에러값이 너무 많음 출전 수가 없어서
#Saber = Saber.drop('나종덕') ## RC 음수 나옴
#Saber = Saber.drop(['RC27', 'RC', 'XR'], axis = 1) 
Saber

OBP       SLG       OPS       GPA      SECA        TA  \
Unnamed: 0                                                               
두산          0.348405  0.378159  0.726564  0.351813  0.309297  0.698722   
KT          0.339951  0.370320  0.710271  0.344211  0.264384  0.656860   
키움          0.354248  0.405143  0.759391  0.372162  0.316594  0.731106   
KIA         0.335268  0.366901  0.702169  0.340648  0.287042  0.653355   
NC          0.352244  0.414410  0.766655  0.378148  0.313755  0.725661   
LG          0.336426  0.375169  0.711595  0.346725  0.280306  0.660294   
삼성          0.321551  0.374910  0.696461  0.342825  0.303328  0.654674   
한화          0.322889  0.354451  0.677339  0.328838  0.264046  0.613515   
롯데          0.318778  0.360133  0.678911  0.331788  0.262607  0.608909   
SK          0.333988  0.375639  0.709628  0.346445  0.281364  0.662416   

                    RC       RC27       XR       ISO         PSR      wOBA  \
Unnamed: 0                                                                   
두산          523.284688  19.380914  607.850  0.108741   81.988235  0.650651   
KT          481.280829  17.825216  561.990  0.097717   88.491620  0.638638   
키움          524.384079  19.421633  598.068  0.122271   92.202128  0.686838   
KIA         424.774092  15.732374  505.946  0.104219   70.713287  0.697901   
NC          587.084357  21.743865  665.952  0.130568   94.958333  0.641782   
LG          480.000407  17.777793  566.392  0.106354   87.500000  0.644728   
삼성          427.573391  15.836052  525.044  0.123055  102.434783  0.681078   
한화          394.318694  14.604396  500.026  0.100116   75.099338  0.652585   
롯데          387.763465  14.361610  485.548  0.105376   65.507463  0.669917   
SK          448.621706  16.615619  527.092  0.111571   86.896552  0.688036   

                 OW%     BABIP  
Unnamed: 0                      
두산          0.623304  0.305222  
KT          0.583279  0.317922  
키움          0.624289  0.328688  
KIA         0.521602  0.307163  
NC          0.675613  0.319081  
LG          0.581983  0.312552  
삼성          0.524879  0.290694  
한화          0.484421  0.310241  
롯데          0.476052  0.306129  
SK          0.548771  0.303951

In [6]:
Scaled_Saber = StandardScaler().fit_transform(Saber)
pd.DataFrame(Scaled_Saber)

0         1         2         3         4         5         6   \
0  1.000128  0.035864  0.446358  0.230923  1.044849  0.822536  0.916817   
1  0.297291 -0.406588 -0.127848 -0.277496 -1.187162 -0.247792  0.221393   
2  1.485803  1.558828  1.603177  1.592024  1.407447  1.650534  0.935019   
3 -0.092019 -0.599530 -0.413353 -0.515864 -0.061159 -0.337399 -0.714142   
4  1.319248  2.081872  1.859159  1.992425  1.266390  1.511319  1.973096   
5  0.004258 -0.132893 -0.081173 -0.109388 -0.395869 -0.159983  0.200195   
6 -1.232333 -0.147498 -0.614496 -0.370238  0.748182 -0.303677 -0.667796   
7 -1.121137 -1.302211 -1.288360 -1.305791 -1.203925 -1.356027 -1.218367   
8 -1.462839 -0.981504 -1.232961 -1.108472 -1.275447 -1.473787 -1.326897   
9 -0.198399 -0.106340 -0.150502 -0.128124 -0.343304 -0.105723 -0.319317   

         7         8         9         10        11        12        13  
0  0.916817  0.991662 -0.219828 -0.239897 -0.696140  0.956119 -0.505500  
1  0.221393  0.140964 -1.293232  0.362257 -1.270302  0.306221  0.793473  
2  0.935019  0.810207  1.097543  0.705817  1.033485  0.972114  1.894592  
3 -0.714142 -0.898645 -0.660132 -1.283856  1.562284 -0.695234 -0.306981  
4  1.973096  2.069447  1.905405  0.961016 -1.120042  1.805459  0.911946  
5  0.200195  0.222621 -0.452228  0.270442 -0.979220  0.285184  0.244243  
6 -0.667796 -0.544380  1.173888  1.653268  0.758166 -0.642023 -1.991385  
7 -1.218367 -1.008461 -1.059673 -0.877747 -0.603718 -1.298937  0.007831  
8 -1.326897 -1.277026 -0.547492 -1.765868  0.224739 -1.434819 -0.412761  
9 -0.319317 -0.506389  0.055748  0.214568  1.090749 -0.254086 -0.635458

In [26]:
pca = PCA(n_components = 3)
PC = pca.fit_transform(Scaled_Saber)
principals = pd.DataFrame(data = PC, columns = ['PC1', 'PC2', 'PC3'])

In [27]:
pd.DataFrame(pca.components_)

0         1         2         3         4         5         6   \
0  0.283649  0.298875  0.306859  0.304993  0.254899  0.303164  0.302595   
1 -0.170874  0.117013  0.000628  0.062701  0.352000  0.077199 -0.131328   
2  0.240568  0.070280  0.145862  0.106691  0.027630  0.122206 -0.084393   

         7         8         9         10        11        12        13  
0  0.302595  0.298214  0.222762  0.195873 -0.068027  0.301323  0.175160  
1 -0.131328 -0.140102  0.444491  0.267882  0.561240 -0.130154 -0.409791  
2 -0.084393 -0.167646 -0.118399 -0.509080  0.589690 -0.083781  0.467491

In [29]:
prin1: 전반적인 타자지표
prin2: SECA, ISO, wOBA 장타율 + 타자생산력
prin3: PSN 호타준족 홈런과 도루 -> 도루 쪽에 더 무게를 둔것같음

SyntaxError: invalid syntax (<ipython-input-29-14983e9084aa>, line 1)

In [19]:
pca.explained_variance_ratio_

array([0.7403376 , 0.12801059, 0.07265382])

In [20]:
sum(pca.explained_variance_ratio_)

0.9410020073166859

In [21]:
## eigen_value 고유값
pca.explained_variance_

array([11.51636265,  1.99127585,  1.1301705 ])

In [22]:
prins = pd.DataFrame(pca.components_)
prins.columns = Saber.columns
prins.index = ['P1', 'P2', 'P3']
prins

OBP       SLG       OPS       GPA      SECA        TA        RC  \
P1  0.283649  0.298875  0.306859  0.304993  0.254899  0.303164  0.302595   
P2 -0.170874  0.117013  0.000628  0.062701  0.352000  0.077199 -0.131328   
P3  0.240568  0.070280  0.145862  0.106691  0.027630  0.122206 -0.084393   

        RC27        XR       ISO       PSR      wOBA       OW%     BABIP  
P1  0.302595  0.298214  0.222762  0.195873 -0.068027  0.301323  0.175160  
P2 -0.131328 -0.140102  0.444491  0.267882  0.561240 -0.130154 -0.409791  
P3 -0.084393 -0.167646 -0.118399 -0.509080  0.589690 -0.083781  0.467491

In [23]:
os.chdir(r'C:\Users\jaij2\OneDrive\바탕 화면\논문\야구데이터\주성분')
prins.to_csv('2019_타자_팀별_주성분3개_규정타석_SM.csv', encoding = 'cp949')

In [ ]:
2번째 주성분은 순장타율이랑 단타를 제외한 장타의 비율이므로 장타를 잘 치는 타자의 성질이고
1번째 주성분은 균등하게 가지고 있는 타자 전반적인 비율

In [23]:
principals['Money_19'] = y
principals

PC1       PC2  Money_19
0    1.696881  0.365679    250000
1    6.704988  2.602923    150000
2    7.223093  0.305748    200000
3    1.161776 -1.240001    150000
4    4.888142  0.510216    150000
..        ...       ...       ...
100 -3.855241  1.116384      4900
101 -3.084625 -0.014060      3000
102 -2.086421  2.833920      4000
103 -4.587613 -0.163248      3000
104 -4.993137  0.635819      2700

[105 rows x 3 columns]

In [27]:
sum(pca.explained_variance_ratio_)

0.9459665264107409

In [134]:
pca.explained_variance_

array([2.39104022, 0.31502439])

In [135]:
PC_score = pca.transform(x)
PC_score

array([[-1.42758619e+00, -2.82538316e-01],
       [-2.18652949e+00, -1.04051511e+00],
       [-1.93275307e+00, -7.57120650e-01],
       [-1.45448461e+00,  2.70477325e-01],
       [-1.94713675e+00, -5.75545399e-01],
       [-1.84663051e+00, -2.06137499e-02],
       [-7.64484918e-01, -1.12553763e-01],
       [-9.86587881e-02, -6.22093410e-01],
       [-9.65071174e-01, -3.41288462e-01],
       [-2.35389049e+00, -6.79359283e-01],
       [-1.54113376e+00, -4.32732508e-01],
       [ 1.47854448e+00,  1.59722374e-01],
       [-1.21442656e+00, -8.95565569e-01],
       [-7.21636085e-01,  1.09839615e-01],
       [-1.73538041e+00, -2.31394256e-01],
       [ 2.64060906e+00, -1.39903010e+00],
       [-1.05344735e+00, -9.43668267e-02],
       [-2.46243575e+00, -4.07604021e-01],
       [-1.63438393e+00,  4.96877337e-01],
       [-1.03361019e+00,  2.11230978e-01],
       [-1.24959305e+00, -7.61325923e-01],
       [-1.72693394e+00, -1.25823236e-03],
       [-2.01546844e+00, -2.97918644e-01],
       [-1.

#### Mulitple Regression

In [136]:
x = principals.drop('Money_19', axis = 1)
x

PC1       PC2
0   -1.427586 -0.282538
1   -2.186529 -1.040515
2   -1.932753 -0.757121
3   -1.454485  0.270477
4   -1.947137 -0.575545
..        ...       ...
100  3.189508 -0.213962
101  2.608368  0.276025
102  2.287844 -0.918622
103  2.501719  1.013709
104  5.000593 -0.401221

[105 rows x 2 columns]

In [137]:
y = principals['Money_19']
y

0      250000
1      150000
2      200000
3      150000
4      150000
        ...  
100      4900
101      3000
102      4000
103      3000
104      2700
Name: Money_19, Length: 105, dtype: int64

In [138]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 42)

In [139]:
len(x_test)

21

In [140]:
LR = LinearRegression()
LR.fit(x_train, y_train)

LinearRegression()

In [141]:
y_prediction = LR.predict(x_test)
y_prediction

array([ 52394.62259726,  22990.18876918,  26446.32984113,  24640.79063289,
        32130.28221751,  45838.78716156, -10318.38082789,  31468.34173844,
        59409.7048854 ,  55397.90829106,  42992.33056225,  36699.19782444,
        33174.28410211,  10307.05356117,  31965.98901888,  66374.22027231,
         6582.63873047,  38486.8375621 ,  64621.34665364,  57129.6730013 ,
        31445.04271182])

In [142]:
score = r2_score(y_test, y_prediction)
print('r2 score is', score)
print('mean_sqrd_error is ==', mean_squared_error(y_test, y_prediction))
print('root_mean_squared error of is == ', np.sqrt(mean_squared_error(y_test, y_prediction)))

r2 score is 0.27315324239632555
mean_sqrd_error is == 2601789041.452781
root_mean_squared error of is ==  51007.73511392935
