In [77]:
import os
import pandas as pd
from sklearn.preprocessing import StandardScaler
import numpy as np
from sklearn.preprocessing import MinMaxScaler


In [68]:
os.chdir(r'C:\Users\jaij2\OneDrive\바탕 화면\논문\야구데이터\전처리')
df_1 = pd.read_csv('2019_타자_DEA_OPS_law.csv', encoding = 'cp949')
df_1.index = df_1['Name']
del df_1['Name']
df_1

PA   AB  RBI  RUN  HIT  H2  H3  HR  SB  CS  ...  LOB   P_HRA_RT  \
Name                                               ...                   
이대호   549  485   88   48  138  23   1  16   0   0  ...  102  28.833333   
박병호   532  432   98   92  121  22   0  33   0   1  ...  110  21.000000   
양의지   459  390   68   61  138  26   0  20   4   3  ...  100  26.500000   
손아섭   568  512   63   78  151  22   1  10  13   8  ...  112  22.333333   
최형우   555  456   86   65  137  31   1  17   0   1  ...  115  26.166667   
...   ...  ...  ...  ...  ...  ..  ..  ..  ..  ..  ...  ...        ...   
임지열    18   15    3    0    2   1   0   0   0   0  ...    4   1.000000   
추재현     1    1    0    0    0   0   0   0   0   0  ...    0   0.000000   
김주형     1    1    0    0    0   0   0   0   0   0  ...    1   0.000000   
양우현     1    1    0    0    0   0   0   0   0   0  ...    0   0.000000   
김성민     4    4    0    0    1   0   0   0   0   0  ...    0   0.000000   

      P_AB_CN  P_HIT_CN  Position  Money_19  Money_20       OBP       SLG  \
Name                                                                        
이대호       131        38         내    250000    250000  0.355191  0.435052   
박병호       117        34         내    150000    200000  0.398496  0.560185   
양의지       110        40         포    200000    200000  0.437908  0.574359   
손아섭       123        36         외    150000    200000  0.359788  0.400391   
최형우       137        36         외    150000    150000  0.412613  0.484649   
...       ...       ...       ...       ...       ...       ...       ...   
임지열         4         1         내      2700      2700  0.235294  0.200000   
추재현         0         0         외      2700      2700  0.000000  0.000000   
김주형         0         0         내      2700      2700  0.000000  0.000000   
양우현         0         0         내      2700      2700  0.000000  0.000000   
김성민         1         0         포      2700      2700  0.250000  0.250000   

           OPS  
Name            
이대호   0.790243  
박병호   0.958681  
양의지   1.012267  
손아섭   0.760179  
최형우   0.897262  
...        ...  
임지열   0.435294  
추재현   0.000000  
김주형   0.000000  
양우현   0.000000  
김성민   0.500000  

[226 rows x 28 columns]

In [69]:
df_2 = df_1.iloc[:, 2:5]
df_3 = df_1.iloc[:, -5:-3]
df_2['Money_19'] = df_3['Money_19']
df_2['Money_20'] = df_3['Money_20']
df_2

RBI  RUN  HIT  Money_19  Money_20
Name                                   
이대호    88   48  138    250000    250000
박병호    98   92  121    150000    200000
양의지    68   61  138    200000    200000
손아섭    63   78  151    150000    200000
최형우    86   65  137    150000    150000
...   ...  ...  ...       ...       ...
임지열     3    0    2      2700      2700
추재현     0    0    0      2700      2700
김주형     0    0    0      2700      2700
양우현     0    0    0      2700      2700
김성민     0    0    1      2700      2700

[226 rows x 5 columns]

In [70]:
scaler = StandardScaler()
scaler.fit(df_2)
scaler.transform(df_2)

array([[ 2.4823648 ,  0.86612687,  1.67099722,  6.58431327,  6.3573762 ],
       [ 2.86325586,  2.51608197,  1.34708343,  3.72409953,  4.97430285],
       [ 1.72058268,  1.35361361,  1.67099722,  5.1542064 ,  4.97430285],
       ...,
       [-0.86947654, -0.93382414, -0.95842061, -0.4889953 , -0.48330458],
       [-0.86947654, -0.93382414, -0.95842061, -0.4889953 , -0.48330458],
       [-0.86947654, -0.93382414, -0.93936685, -0.4889953 , -0.48330458]])

In [71]:
df_4 = pd.DataFrame(scaler.transform(df_2))
df_4.columns = ['RBI', 'RUN', 'HIT', 'Money_19', 'Money_20']

In [72]:
df_4.index = df_2.index
df_4 = round(df_4, 3)
df_4

RBI    RUN    HIT  Money_19  Money_20
Name                                         
이대호   2.482  0.866  1.671     6.584     6.357
박병호   2.863  2.516  1.347     3.724     4.974
양의지   1.721  1.354  1.671     5.154     4.974
손아섭   1.530  1.991  1.919     3.724     4.974
최형우   2.406  1.504  1.652     3.724     3.591
...     ...    ...    ...       ...       ...
임지열  -0.755 -0.934 -0.920    -0.489    -0.483
추재현  -0.869 -0.934 -0.958    -0.489    -0.483
김주형  -0.869 -0.934 -0.958    -0.489    -0.483
양우현  -0.869 -0.934 -0.958    -0.489    -0.483
김성민  -0.869 -0.934 -0.939    -0.489    -0.483

[226 rows x 5 columns]

In [73]:
df_4.to_csv('2019_타자_DEA_OPS_law_std.csv', encoding = 'cp949')

In [196]:
df_6 = round(df_4, 3)
df_6 = df_6 * 1000
df_6

RBI     RUN     HIT  Money_19  Money_20
Name                                            
이대호   2482.0   866.0  1671.0    6584.0    6357.0
박병호   2863.0  2516.0  1347.0    3724.0    4974.0
양의지   1721.0  1354.0  1671.0    5154.0    4974.0
손아섭   1530.0  1991.0  1919.0    3724.0    4974.0
최형우   2406.0  1504.0  1652.0    3724.0    3591.0
...      ...     ...     ...       ...       ...
임지열   -755.0  -934.0  -920.0    -489.0    -483.0
추재현   -869.0  -934.0  -958.0    -489.0    -483.0
김주형   -869.0  -934.0  -958.0    -489.0    -483.0
양우현   -869.0  -934.0  -958.0    -489.0    -483.0
김성민   -869.0  -934.0  -939.0    -489.0    -483.0

[226 rows x 5 columns]

In [ ]:
df_6.to_csv('')

In [187]:
#inpu = df_4['Money_19'].to_numpy()
inpu = np.array([[m] for m in df_4.iloc[:, 3].to_list()])
outpu = df_4.iloc[:, :3].to_numpy()

In [197]:
#inpu = df_4['Money_19'].to_numpy()
inpu = np.array([[m] for m in df_6.iloc[:, 3].to_list()])
outpu = df_6.iloc[:, :3].to_numpy()

In [82]:
scaler = MinMaxScaler()
scaler.fit(df_2)
scaler.transform(df_2)

array([[0.84615385, 0.42857143, 0.71502591, 1.        , 1.        ],
       [0.94230769, 0.82142857, 0.62694301, 0.59563283, 0.79781642],
       [0.65384615, 0.54464286, 0.71502591, 0.79781642, 0.79781642],
       ...,
       [0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.00518135, 0.        , 0.        ]])

In [84]:
df_5 = pd.DataFrame(scaler.transform(df_2))
df_5.columns = ['RBI', 'RUN', 'HIT', 'Money_19', 'Money_20']
df_5.index = df_2.index
df_5

RBI       RUN       HIT  Money_19  Money_20
Name                                                  
이대호   0.846154  0.428571  0.715026  1.000000  1.000000
박병호   0.942308  0.821429  0.626943  0.595633  0.797816
양의지   0.653846  0.544643  0.715026  0.797816  0.797816
손아섭   0.605769  0.696429  0.782383  0.595633  0.797816
최형우   0.826923  0.580357  0.709845  0.595633  0.595633
...        ...       ...       ...       ...       ...
임지열   0.028846  0.000000  0.010363  0.000000  0.000000
추재현   0.000000  0.000000  0.000000  0.000000  0.000000
김주형   0.000000  0.000000  0.000000  0.000000  0.000000
양우현   0.000000  0.000000  0.000000  0.000000  0.000000
김성민   0.000000  0.000000  0.005181  0.000000  0.000000

[226 rows x 5 columns]

In [94]:
df_5.to_csv('2019_타자_DEA_OPS_law_minmax.csv', encoding = 'cp949')

In [162]:
inpu_2 = df_5.iloc[:, 3].to_numpy()

ar_list = []
for k in range(0, len(df_5)) :
    ar_list.append(df_5.iloc[k, :3].to_numpy())
np.array(ar_list)

outpu_2 = np.array(ar_list)

In [183]:
#np.array(df_5.iloc[:, 3].to_list())
np.array([[l] for l in df_5.iloc[:, 3].to_list()])

array([[1.00000000e+00],
       [5.95632835e-01],
       [7.97816417e-01],
       [5.95632835e-01],
       [5.95632835e-01],
       [5.14759402e-01],
       [5.55196118e-01],
       [4.94541043e-01],
       [4.94541043e-01],
       [4.74322685e-01],
       [4.74322685e-01],
       [3.12575819e-01],
       [2.92357461e-01],
       [2.51920744e-01],
       [2.84270117e-01],
       [2.31702386e-01],
       [1.50828953e-01],
       [1.18479579e-01],
       [1.42741609e-01],
       [2.11484027e-01],
       [3.93449252e-01],
       [1.18479579e-01],
       [2.31702386e-01],
       [1.91265669e-01],
       [1.44763445e-01],
       [1.10392236e-01],
       [1.10392236e-01],
       [1.44763445e-01],
       [1.50828953e-01],
       [1.50828953e-01],
       [1.50828953e-01],
       [8.20865346e-02],
       [1.50828953e-01],
       [2.72139102e-01],
       [1.30610594e-01],
       [8.81520421e-02],
       [1.14435908e-01],
       [1.34654266e-01],
       [1.10392236e-01],
       [1.10392236e-01],


In [184]:
#inpu_2 = df_5.iloc[:, 3].to_numpy()
inpu_2 = np.array([[l] for l in df_5.iloc[:, 3].to_list()])
outpu_2 = df_5.iloc[:, :3].to_numpy()

In [198]:
import numpy as np
from scipy.optimize import fmin_slsqp


class DEA(object):

    def __init__(self, inputs, outputs):

        # supplied data
        self.inputs = inputs
        self.outputs = outputs

        # parameters
        self.n = inputs.shape[0]
        self.m = inputs.shape[1]
        self.r = outputs.shape[1]

        # iterators
        self.unit_ = range(self.n)
        self.input_ = range(self.m)
        self.output_ = range(self.r)

        # result arrays
        self.output_w = np.zeros((self.r, 1), dtype=np.float)  # output weights
        self.input_w = np.zeros((self.m, 1), dtype=np.float)  # input weights
        self.lambdas = np.zeros((self.n, 1), dtype=np.float)  # unit efficiencies
        self.efficiency = np.zeros_like(self.lambdas)  # thetas
    def __efficiency(self, unit):
        # compute efficiency
        denominator = np.dot(self.inputs, self.input_w)
        numerator = np.dot(self.outputs, self.output_w)

        return (numerator/denominator)[unit]
    def __target(self, x, unit):

        in_w, out_w, lambdas = x[:self.m], x[self.m:(self.m+self.r)], x[(self.m+self.r):]  # unroll the weights
        denominator = np.dot(self.inputs[unit], in_w)
        numerator = np.dot(self.outputs[unit], out_w)

        return numerator/denominator

    def __constraints(self, x, unit):

        in_w, out_w, lambdas = x[:self.m], x[self.m:(self.m+self.r)], x[(self.m+self.r):]  # unroll the weights
        constr = []  # init the constraint array

        # for each input, lambdas with inputs
        for input in self.input_:
            t = self.__target(x, unit)
            lhs = np.dot(self.inputs[:, input], lambdas)
            cons = t*self.inputs[unit, input] - lhs
            constr.append(cons)

        # for each output, lambdas with outputs
        for output in self.output_:
            lhs = np.dot(self.outputs[:, output], lambdas)
            cons = lhs - self.outputs[unit, output]
            constr.append(cons)

        # for each unit
        for u in self.unit_:
            constr.append(lambdas[u])

        return np.array(constr)

    def __optimize(self):

        d0 = self.m + self.r + self.n
        # iterate over units
        for unit in self.unit_:
            # weights
            x0 = np.random.rand(d0) - 0.5
            x0 = fmin_slsqp(self.__target, x0, f_ieqcons=self.__constraints, args=(unit,))
            # unroll weights
            self.input_w, self.output_w, self.lambdas = x0[:self.m], x0[self.m:(self.m+self.r)], x0[(self.m+self.r):]
            self.efficiency[unit] = self.__efficiency(unit)

    def fit(self):
        self.__optimize()  # optimize
        return self.efficiency


if __name__ == "__main__":
    X = inpu
    y = outpu
    dea = DEA(X,y)
    rs = dea.fit()
    print(rs)

Positive directional derivative for linesearch    (Exit mode 8)
            Current function value: -2895.47098337863
            Iterations: 36
            Function evaluations: 7417
            Gradient evaluations: 32
Iteration limit reached    (Exit mode 9)
            Current function value: -1466.1105927069823
            Iterations: 100
            Function evaluations: 22225
            Gradient evaluations: 96
Positive directional derivative for linesearch    (Exit mode 8)
            Current function value: -232.19419971468236
            Iterations: 18
            Function evaluations: 3246
            Gradient evaluations: 14
Optimization terminated successfully    (Exit mode 0)
            Current function value: -102.90224650005658
            Iterations: 44
            Function evaluations: 10221
            Gradient evaluations: 44
Optimization terminated successfully    (Exit mode 0)
            Current function value: -205.04582057981608
            Iterations: 34
   

Optimization terminated successfully    (Exit mode 0)
            Current function value: -1720.6038223028074
            Iterations: 52
            Function evaluations: 12064
            Gradient evaluations: 52
Optimization terminated successfully    (Exit mode 0)
            Current function value: -6705.246025956002
            Iterations: 17
            Function evaluations: 3027
            Gradient evaluations: 13
Optimization terminated successfully    (Exit mode 0)
            Current function value: 7.248555496357347
            Iterations: 6
            Function evaluations: 1398
            Gradient evaluations: 6
Optimization terminated successfully    (Exit mode 0)
            Current function value: -187112.5392059758
            Iterations: 22
            Function evaluations: 4218
            Gradient evaluations: 18
Inequality constraints incompatible    (Exit mode 4)
            Current function value: -1205211.8304324837
            Iterations: 17
            Funct

Optimization terminated successfully    (Exit mode 0)
            Current function value: -64.42680280046692
            Iterations: 38
            Function evaluations: 8818
            Gradient evaluations: 38
Optimization terminated successfully    (Exit mode 0)
            Current function value: -58.99872206805775
            Iterations: 45
            Function evaluations: 10425
            Gradient evaluations: 45
Optimization terminated successfully    (Exit mode 0)
            Current function value: -8.312416680050246
            Iterations: 36
            Function evaluations: 8351
            Gradient evaluations: 36
Optimization terminated successfully    (Exit mode 0)
            Current function value: -12.90415581346174
            Iterations: 51
            Function evaluations: 11824
            Gradient evaluations: 51
Optimization terminated successfully    (Exit mode 0)
            Current function value: -7.347538949122137
            Iterations: 42
            Fu

Optimization terminated successfully    (Exit mode 0)
            Current function value: -6.296280460823937
            Iterations: 44
            Function evaluations: 10204
            Gradient evaluations: 44
Optimization terminated successfully    (Exit mode 0)
            Current function value: -1.6007944697137582
            Iterations: 45
            Function evaluations: 10431
            Gradient evaluations: 45
Optimization terminated successfully    (Exit mode 0)
            Current function value: -38.41672039151245
            Iterations: 39
            Function evaluations: 9036
            Gradient evaluations: 39
Optimization terminated successfully    (Exit mode 0)
            Current function value: -1.256620556930078
            Iterations: 40
            Function evaluations: 9251
            Gradient evaluations: 40
Optimization terminated successfully    (Exit mode 0)
            Current function value: -0.8170096688553805
            Iterations: 52
            

Optimization terminated successfully    (Exit mode 0)
            Current function value: -129.09087690075094
            Iterations: 66
            Function evaluations: 15297
            Gradient evaluations: 66
Optimization terminated successfully    (Exit mode 0)
            Current function value: -6.032219591106056
            Iterations: 43
            Function evaluations: 9962
            Gradient evaluations: 43
Iteration limit reached    (Exit mode 9)
            Current function value: -459.06334287920066
            Iterations: 100
            Function evaluations: 23115
            Gradient evaluations: 100
Optimization terminated successfully    (Exit mode 0)
            Current function value: -15.864993420017104
            Iterations: 52
            Function evaluations: 12059
            Gradient evaluations: 52
Optimization terminated successfully    (Exit mode 0)
            Current function value: -9.108373499030334
            Iterations: 38
            Function 

Optimization terminated successfully    (Exit mode 0)
            Current function value: -32.70396806961573
            Iterations: 40
            Function evaluations: 9275
            Gradient evaluations: 40
Optimization terminated successfully    (Exit mode 0)
            Current function value: -1.5582931423851871
            Iterations: 43
            Function evaluations: 9970
            Gradient evaluations: 43
Optimization terminated successfully    (Exit mode 0)
            Current function value: -1166.6954749347108
            Iterations: 30
            Function evaluations: 6971
            Gradient evaluations: 30
Optimization terminated successfully    (Exit mode 0)
            Current function value: -31.290038788235197
            Iterations: 36
            Function evaluations: 8352
            Gradient evaluations: 36
Optimization terminated successfully    (Exit mode 0)
            Current function value: -73.57649128028277
            Iterations: 40
            F

In [170]:
inpu_2[0]

1.0

In [174]:
outpu_2[0]

array([0.84615385, 0.42857143, 0.71502591])

In [173]:
outpu_2 = df_5.iloc[:, :3].to_numpy()